from __future__ import annotations

from typing import Any, Protocol


class MarketDataRepository(Protocol):
    def init_schema(self) -> None: ...
    def universe_summary(self) -> dict[str, Any]: ...
    def upsert_symbols(self, items: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
    def list_symbols(self) -> list[dict[str, Any]]: ...
    def get_symbol(self, symbol: str) -> dict[str, Any]: ...
    def update_symbol_metadata(self, symbol: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_symbol_snapshots(self) -> list[dict[str, Any]]: ...
    def create_import_batch(self, symbols: list[str], source: str, notes: str | None = None) -> dict[str, Any]: ...
    def list_import_batches(self) -> list[dict[str, Any]]: ...
    def get_import_batch(self, batch_id: str) -> dict[str, Any]: ...
    def ingest_daily_bars(
        self,
        symbol: str,
        bars: list[dict[str, Any]],
        *,
        source: str = "manual",
        batch_id: str | None = None,
    ) -> dict[str, Any]: ...
    def list_daily_bars(self, symbol: str, limit: int = 60) -> list[dict[str, Any]]: ...
